name: Android Unit Tests

on:
  push:
    branches:
      - main  # Runs tests on push to `main`
      - dev   # Runs tests on push to `dev`
  pull_request:
    branches:
      - main  # Runs tests on pull requests to `main`

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Use OpenJDK (Temurin)
          java-version: '17'       # Java version required for Android

      - name: Set up Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Grant Execute Permission for Gradlew
        run: chmod +x gradlew

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest  # Runs unit tests for debug build
